### PR TITLE
update haskell-nix

### PR DESCRIPTION
**Pull request by cab404**
yeah, we need it again

### CODE REVIEW

**Comment by cab404** [comment]
I didn't reorder it, nix 2.10.3 did

**Review by balsoft — CHANGES_REQUESTED** [review]
This changes it to an "indirect" entry. Please use `nix registry pin` and not `nix registry add`.

**Comment by cab404** [comment]
~looks like it already was indirect @balsoft~

ooof, ok

**Comment by cab404** [comment]
oh, okay
it was not

**Review by balsoft — APPROVED** [review]
LGTM

**Pull request merged**
